name: Build APK

on:
  push:
    branches: [ main, master ] # Se activa al subir cambios a estas ramas
  workflow_dispatch: # Permite ejecutarlo manualmente si quieres

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            build-essential \
            git zip unzip \
            openjdk-17-jdk \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev

          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33

      - name: Build APK
        run: |
          # Usamos "yes |" para aceptar automáticamente las licencias del SDK de Android
          yes | buildozer android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4 # Actualizado a v4 para que no de error
        with:
          name: VideoDownloader-APK
          path: bin/*.apk
          
