name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            build-essential \
            git zip unzip \
            openjdk-17-jdk \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev

          pip3 install --upgrade pip
          # Forzamos Cython 0.29.33 que es el que mejor se lleva con Kivy 2.2.1
          pip3 install "cython<3.0.0" buildozer setuptools

      - name: Build APK
        run: |
          # Aceptamos licencias y ejecutamos buildozer con logs detallados
          yes | buildozer android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: VideoDownloader-APK
          path: bin/*.apk
          
